type EntityID = usize
type entity(id: EntityID, token: String, label: String, start_idx: usize, end_idx: usize, src: String)

// The ground truth graph
rel entity(1, "acute", "OBS-DA", 1, 2, "GT")
rel entity(2, "process", "OBS-DA", 3, 4, "GT")
rel entity(3, "consolidation", "OBS-DA", 5, 6, "GT")

rel result(id) = entity(id, token, label, start_idx, end_idx, src), ablate_entity(id, token, label, start_idx, end_idx, src)
query result